[package]
name = "shadow-rs"
version = "2.0.0-pre"
edition = "2018"
publish = false

[lib]
path = "lib.rs"
crate-type = ["staticlib"]

[dependencies]
lazy_static = "1.4.0"
libc = "0.2"
log = "0.4"
log-bindings = { path = "../support/logger/rust_bindings" }
nix = "0.22.0"
rand = "0.8.0"
rand_chacha = "0.3.0"
rand_core = "0.6.0"
regex = "1"
